from typing import Protocol, Any

class TableGateway(Protocol):
    def insert      (self, data: dict)                   -> Any: ...
    def update      (self, filters: dict, updates: dict) -> Any: ...
    def select_one  (self, filters: dict)                -> Any: ...
    def select_many (self, filters: dict)                -> Any: ...
    def delete      (self, filters: dict)                -> Any: ...
