from __future__ import annotations
from typing import Protocol, TypeVar

T = TypeVar("T")

class TableGateway(Protocol[T]):
    def insert      (self, data: dict)                   -> T: ...
    def update      (self, filters: dict, updates: dict) -> T: ...
    def select_one  (self, filters: dict)                -> T | None: ...
    def select_many (self, filters: dict)                -> list[T]: ...
    def delete      (self, filters: dict)                -> bool: ...