# app/db/ports/sessions_repo.py
from typing import Protocol, Any

class SessionsRepo(Protocol):
    """ Interface for managing sessions in the database. """
    def create(self, session: dict) -> Any: ...
    def get(self, session_id: str) -> Any: ...
    def list_for_user(self, user_id: str) -> Any: ...
    def update(self, session_id: str, updates: dict) -> Any: ...
    def delete(self, session_id: str) -> Any: ...