# app/db/ports/table_gateway.py
from typing import Protocol, Any

class TableGateway(Protocol):
    """Generic table gateway interface for CRUD operations."""
    def insert(self, data: dict) -> Any: ...
    def update(self, filters: dict, updates: dict) -> Any: ...
    def select_one(self, filters: dict) -> Any: ...
    def select_many(self, filters: dict) -> Any: ...
    def delete(self, filters: dict) -> Any: ...
