from __future__ import annotations
from typing import Protocol, BinaryIO

class BlobStorage(Protocol):
    def upload(self, container: str, blob: str, data: bytes | BinaryIO, *, content_type: str | None = None) -> str: ...
    def download(self, container: str, blob: str) -> bytes: ...
    def delete(self, container: str, blob: str) -> None: ...
    def url(self, container: str, blob: str, *, public: bool = False) -> str: ...
    def generate_sas_url(self, container: str, blob: str, *, expiry_seconds: int = 3600) -> str: ...
