from typing import Protocol

from app.core.constants.db.supabase_constants import SessionColumn
from app.models.session import SessionDB

class SessionsRepo(Protocol):
    def create(self, session: dict[SessionColumn, str]) -> SessionDB: ...
    def get_for_user(self, session_id: str, user_id: str) -> SessionDB | None: ...
    def list_for_user(self, user_id: str) -> list[SessionDB]: ...
    def update(self, session_id: str, updates: dict) -> SessionDB: ...
    def delete(self, session_id: str) -> bool: ...