from typing import Protocol, Any

class SessionsRepo(Protocol):
    def create(self, session: dict) -> Any: ...
    def get_for_user(self, session_id: str, user_id: str): ...
    def list_for_user(self, user_id: str) -> Any: ...
    def update(self, session_id: str, updates: dict) -> Any: ...
    def delete(self, session_id: str) -> Any: ...