from typing import Protocol, Optional, Any, Dict

class UserDefaultsRepo(Protocol):
    def get     (self, user_id: str)                            -> Optional[Dict[str, Any]]: ...
    def upsert  (self, user_id: str, payload: Dict[str, Any])   -> Dict[str, Any]: ...
