from typing import Protocol, Any

class UsersRepo(Protocol):
    def create      (self, user: dict)                      -> Any: ...
    def get         (self, user_id: str)                    -> Any: ...
    def list_all    (self)                                  -> Any: ...
    def update      (self, user_id: str, updates: dict)     -> Any: ...
    def delete      (self, user_id: str)                    -> Any: ...